### ISSUE TITLE
Is it possible to provide public input data?

### ISSUE THREAD

**Issue by yuemos** [mabulnaga/placenta-flattening#2]
Hello, I am a master student majoring in computer science. I am very interested in your work and hope to reproduce the results, but because there is no MRI scan data, I cannot successfully run the program to observe the effect. If you can provide the program input data, I will  really appreciate.

**Comment by mabulnaga** [comment]
Hello, thank you for your interest in the work! Unfortunately the data used to validate this method is not public.

**Comment by yuemos** [comment]
Thank you very much for your reply, I understand your reasoning. I am still very interested in your topic. I may have some technical questions in the future and hope to hear from you.

**Comment by mabulnaga** [comment]
Of course! Happy to help!
